services:
  plastiki.database:
    image: postgres:latest
    container_name: plastiki.database
    environment:
      - POSTGRES_DB=plastiki
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
      
