services:
  prodtrack.database:
    image: postgres:latest
    container_name: prodtrack.database
    environment:
      - POSTGRES_DB=prodtrack
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
      
